language: go

os:
  - linux
  - windows
  - osx

go:
  - 1.12.1

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then sed -i '' 's/trace = false/trace = true/g' notrace.go; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sed -i 's/trace = false/trace = true/g' notrace.go; fi

script:
  - go get -t ./...
  - go test -v -race -coverprofile=coverage.txt -coverpkg ./... ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)